# Generated by Django 4.2.1 on 2023-05-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('rol', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Nodo', 'Nodo'), ('SubAdmin', 'SubAdmin')], max_length=50, null=True, verbose_name='Rol de usuario')),
                ('usuario_activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('usuario_admin', models.BooleanField(default=False, verbose_name='Usuario administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
